branches:
  only: 
    - next
env:
  global:
    - ANDROID_PACKAGE='app-debug.apk'
    - ANDROID_PACKAGE_NEXT='demo-debug-next.apk'
    - ANDROID_PACKAGE_FOLDER=$TRAVIS_BUILD_DIR/demo/platforms/android/app/build/outputs/apk/debug
    - ANDROID_SAUCE_STORAGE="https://saucelabs.com/rest/v1/storage/$SAUCE_USER/$ANDROID_PACKAGE_NEXT?overwrite=true"
    - IOS_PACKAGE_NEXT='demo-next.zip'
    - IOS_PACKAGE_FOLDER=$TRAVIS_BUILD_DIR/demo/platforms/ios/build/emulator
    - IOS_SAUCE_STORAGE="https://saucelabs.com/rest/v1/storage/$SAUCE_USER/$IOS_PACKAGE_NEXT?overwrite=true"

matrix:
  include:
    - stage: "Build"
      env: 
        - BuildAndroid="26"
      language: android
      os: linux
      jdk: oraclejdk8
      before_install: 
        - nvm install 8.11.4
      before_script:
        - cd ../demo && tns platform add android@next
        - cd ../demo-angular && tns platform add android@next
      script:
        - cd ../demo && npm run ci.android.build && cd ../demo-angular && npm run ci.android.build
        - "curl -u $SAUCE_USER:$SAUCE_KEY -X POST -H 'Content-Type: application/octet-stream' $ANDROID_SAUCE_STORAGE --data-binary @$ANDROID_PACKAGE_FOLDER/$ANDROID_PACKAGE"
    - os: osx
      env: 
        - BuildiOS="11"
        - Xcode="9.4"
      osx_image: xcode9.4
      language: node_js 
      node_js: "8"
      jdk: oraclejdk8
      before_script:
        - cd ../demo && tns platform add ios@next
        - cd ../demo-angular && tns platform add ios@next
      script: 
        - cd ../demo && npm run ci.ios.build && cd ../demo-angular && npm run ci.ios.build
        - cd $IOS_PACKAGE_FOLDER && zip -r $IOS_PACKAGE_NEXT demo.app
        - "curl -u $SAUCE_USER:$SAUCE_KEY -X POST -H 'Content-Type: application/octet-stream' $IOS_SAUCE_STORAGE --data-binary @$IOS_PACKAGE_FOLDER/$IOS_PACKAGE_NEXT"
    - os: osx
      env:
        - Webpack="iOS"
      osx_image: xcode9.4
      language: node_js 
      node_js: "8"
      jdk: oraclejdk8
      before_script:
        - cd ../demo && tns platform add ios@next
        - cd ../demo-angular && tns platform add ios@next
      script:
        - cd ../demo && npm run build.plugin && npm i && tns build ios --bundle --env.uglify
        - cd ../publish && sh pack.sh && cp package/*.tgz ../demo-angular/package.tgz
        - cd ../demo-angular && tns plugin add package.tgz && npm i && tns build ios --bundle --env.uglify --env.aot
    - os: linux
      language: android
      env:
        - Webpack="Android"
      jdk: oraclejdk8
      before_install: nvm install 8.11.4
      before_script:
        - cd ../demo && tns platform add android@next
        - cd ../demo-angular && tns platform add android@next
      script:
        - cd ../demo && npm run build.plugin && npm i && tns build android --bundle --env.uglify
        - cd ../publish && sh pack.sh && cp package/*.tgz ../demo-angular/package.tgz
        - cd ../demo-angular && tns plugin add package.tgz && npm i && tns build android --bundle --env.uglify --env.aot
    - stage: "UI Tests"
      env: 
        - Android="23"
      language: node_js
      os: linux
      node_js: "8"
      install: true
      script:
        - npm i -g appium
        - cd demo && npm i
        - travis_retry npm run e2e -- --runType android23 --sauceLab --reuseDevice --appPath $ANDROID_PACKAGE_NEXT
    - os: linux
      env: 
        - iOS="10"
      language: node_js 
      node_js: "8"
      install: true
      script: 
        - npm i -g appium
        - cd demo && npm i
        - travis_wait travis_retry npm run e2e -- --runType sim103iPhone6 --sauceLab --reuseDevice --appPath $IOS_PACKAGE_NEXT

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-26
    - android-23
    - extra-android-m2repository

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
    directories:
        - .nvm
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/

install:
    - npm install -g nativescript@next
    - tns usage-reporting disable
    - tns error-reporting disable
    - pip install six
    - cd src
    - npm install tns-core-modules@next -D
    - npm install nativescript-angular@next -D
    - cd ../demo
    - npm install nativescript-dev-webpack@next -D
    - ./node_modules/.bin/update-ns-webpack --deps
    - npm install tns-core-modules@next -P
    - npm install nativescript-dev-typescript@next -D
    - cd ../demo-angular
    - npm install nativescript-dev-webpack@next -D
    - ./node_modules/.bin/update-ns-webpack --deps
    - ./node_modules/.bin/update-app-ng-deps
    - npm install tns-core-modules@next -P
    - npm install nativescript-angular@next -P
    - npm install nativescript-dev-typescript@next -D
